apiVersion: v1
kind: Secret
metadata:
  name: task-tracker-secrets
type: Opaque
stringData:
  SECRET_KEY: "k8s-local-secret-change-me"
  DATABASE_URL: "postgresql://postgres.xucijbbpgweyzvopnfej:ruWwac-0mocce-wefxoj@aws-1-ap-south-1.pooler.supabase.com:6543/postgres"
